import type { Opportunity } from '../components/launchpad/types';

export const opportunities: Opportunity[] = [
  {
    id: 'sih-2026',
    title: 'Smart India Hackathon 2026',
    organizer: 'Government of India & AICTE',
    category: 'hackathon',
    description: 'India\'s largest open innovation platform where students solve real-world problems posed by government ministries and industry leaders.',
    deadline: '2026-08-15',
    applyUrl: 'https://www.sih.gov.in/',
    location: 'Pan-India (Multiple Nodal Centers)',
    eligibility: 'All years',
    tags: ['innovation', 'government', 'problem-solving', 'team', 'hardware', 'software'],
    isFeatured: true,
  },
  {
    id: 'gsoc-2026',
    title: 'Google Summer of Code 2026',
    organizer: 'Google',
    category: 'open-source',
    description: 'A global mentorship program where contributors work on open-source projects with stipends. Build real-world software used by millions.',
    deadline: '2026-04-08',
    applyUrl: 'https://summerofcode.withgoogle.com/',
    location: 'Remote',
    eligibility: 'All years (18+)',
    tags: ['open-source', 'python', 'javascript', 'golang', 'stipend', 'mentorship'],
    isFeatured: true,
  },
  {
    id: 'mlh-ghw-2026',
    title: 'MLH Global Hack Week',
    organizer: 'Major League Hacking',
    category: 'hackathon',
    description: 'A week-long hackathon with daily challenges, workshops, and prizes. Perfect for beginners and experienced hackers alike.',
    deadline: '2026-10-01',
    applyUrl: 'https://ghw.mlh.io/',
    location: 'Online',
    eligibility: 'All years',
    tags: ['web', 'ai', 'beginner-friendly', 'workshops', 'prizes'],
    isFeatured: false,
  },
  {
    id: 'hacktoberfest-2026',
    title: 'Hacktoberfest 2026',
    organizer: 'DigitalOcean',
    category: 'open-source',
    description: 'Contribute to open-source projects during October. Make 4 quality pull requests and earn digital badges and recognition.',
    deadline: '2026-10-31',
    applyUrl: 'https://hacktoberfest.com/',
    location: 'Online',
    eligibility: 'All years',
    tags: ['open-source', 'git', 'github', 'beginner-friendly', 'swag'],
    isFeatured: false,
  },
  {
    id: 'amazon-ml-summer',
    title: 'Amazon ML Summer School',
    organizer: 'Amazon',
    category: 'internship',
    description: 'An intensive machine learning program taught by Amazon scientists. Covers supervised learning, deep learning, NLP, and more.',
    deadline: '2026-06-30',
    applyUrl: 'https://www.amazonmlsummerschool.com/',
    location: 'Online',
    eligibility: '2nd year+',
    tags: ['ai', 'machine-learning', 'deep-learning', 'nlp', 'amazon'],
    isFeatured: true,
  },
  {
    id: 'mitacs-globalink',
    title: 'MITACS Globalink Research Internship',
    organizer: 'MITACS Canada',
    category: 'internship',
    description: 'A 12-week research internship at top Canadian universities. Fully funded including travel, accommodation, and stipend.',
    deadline: '2026-09-15',
    applyUrl: 'https://www.mitacs.ca/our-programs/globalink-research-internship-students/',
    location: 'Canada',
    eligibility: '2nd & 3rd year',
    tags: ['research', 'international', 'funded', 'canada', 'stipend'],
    isFeatured: false,
  },
  {
    id: 'github-externship',
    title: 'GitHub Externship Program',
    organizer: 'GitHub India',
    category: 'internship',
    description: 'A fellowship program connecting Indian students with open-source mentors at GitHub. Gain real industry experience.',
    deadline: '2026-07-31',
    applyUrl: 'https://github.com/externship',
    location: 'Remote (India)',
    eligibility: '2nd year+',
    tags: ['open-source', 'git', 'mentorship', 'fellowship', 'software-engineering'],
    isFeatured: false,
  },
  {
    id: 'google-kickstart',
    title: 'Google Competitive Programming',
    organizer: 'Google',
    category: 'hackathon',
    description: 'Algorithmic coding competitions hosted by Google. Test your DSA skills against the best programmers worldwide.',
    deadline: '2026-12-31',
    applyUrl: 'https://g.co/competitive-programming',
    location: 'Online',
    eligibility: 'All years',
    tags: ['dsa', 'algorithms', 'competitive-programming', 'google'],
    isFeatured: false,
  },
  {
    id: 'aws-cloud-club',
    title: 'AWS Cloud Club Workshop Series',
    organizer: 'Amazon Web Services',
    category: 'workshop',
    description: 'Hands-on cloud computing workshops covering AWS services, serverless, and cloud architecture. Free certification vouchers for participants.',
    deadline: '2026-09-01',
    applyUrl: 'https://aws.amazon.com/developer/community/students/',
    location: 'Hyderabad + Online',
    eligibility: 'All years',
    tags: ['cloud', 'aws', 'devops', 'serverless', 'certification'],
    isFeatured: false,
  },
  {
    id: 'buildspace-s5',
    title: 'Buildspace Nights & Weekends',
    organizer: 'Buildspace',
    category: 'hackathon',
    description: 'A 6-week program where you build your idea into a real product. Demo day in San Francisco. Open to builders worldwide.',
    deadline: '2026-07-15',
    applyUrl: 'https://buildspace.so/',
    location: 'Online + San Francisco Demo Day',
    eligibility: 'All years',
    tags: ['startup', 'product', 'web', 'ai', 'building'],
    isFeatured: false,
  },
  {
    id: 'leetcode-biweekly',
    title: 'LeetCode Biweekly Contests',
    organizer: 'LeetCode',
    category: 'hackathon',
    description: 'Regular competitive programming contests to sharpen your DSA skills. Great preparation for technical interviews.',
    deadline: '2026-12-31',
    applyUrl: 'https://leetcode.com/contest/',
    location: 'Online',
    eligibility: 'All years',
    tags: ['dsa', 'algorithms', 'interview-prep', 'competitive-programming'],
    isFeatured: false,
  },
  {
    id: 'unstop-hiring',
    title: 'Unstop Hiring Challenges',
    organizer: 'Unstop (formerly Dare2Compete)',
    category: 'internship',
    description: 'Solve coding and case-study challenges from top companies like Google, Microsoft, and Amazon to land internships directly.',
    deadline: '2026-12-31',
    applyUrl: 'https://unstop.com/competitions',
    location: 'Online',
    eligibility: 'All years',
    tags: ['hiring', 'internship', 'coding', 'interview-prep', 'companies'],
    isFeatured: false,
  },
  {
    id: 'cybersec-ctf-hyderabad',
    title: 'CyberSec CTF Hyderabad 2026',
    organizer: 'Hyderabad Security Community',
    category: 'conference',
    description: 'A capture-the-flag competition and security conference in Hyderabad. Network with local security professionals and test your skills.',
    deadline: '2026-11-15',
    applyUrl: 'https://ctftime.org/',
    location: 'Hyderabad',
    eligibility: 'All years',
    tags: ['cybersecurity', 'ctf', 'networking', 'hyderabad', 'hacking'],
    isFeatured: false,
  },
  {
    id: 'microsoft-imagine-cup',
    title: 'Microsoft Imagine Cup 2026',
    organizer: 'Microsoft',
    category: 'hackathon',
    description: 'A global technology competition where students create innovative solutions using Microsoft technologies. Grand prize: $100,000.',
    deadline: '2026-10-01',
    applyUrl: 'https://imaginecup.microsoft.com/',
    location: 'Online + Finals in Seattle',
    eligibility: 'All years',
    tags: ['ai', 'azure', 'cloud', 'innovation', 'microsoft', 'prize'],
    isFeatured: true,
  },
  {
    id: 'gen-ai-study-jams',
    title: 'Google Gen AI Study Jams',
    organizer: 'Google Developer Student Clubs',
    category: 'workshop',
    description: 'Free hands-on workshops on generative AI, Gemini API, and Google Cloud. Earn skill badges and Google Cloud credits.',
    deadline: '2026-08-31',
    applyUrl: 'https://gdsc.community.dev/',
    location: 'Online + Campus Events',
    eligibility: 'All years',
    tags: ['ai', 'generative-ai', 'google', 'cloud', 'workshops', 'free'],
    isFeatured: false,
  },
];
