import type { RoadmapDomain } from '../components/launchpad/types';

export const roadmapDomains: RoadmapDomain[] = [
  {
    id: 'web-dev',
    title: 'Web Development',
    icon: 'fas fa-code',
    color: '#3b82f6',
    description: 'Build modern, responsive web applications from frontend to backend.',
    nodes: [
      {
        id: 'web-html-css',
        title: 'HTML & CSS Fundamentals',
        description: 'Learn semantic HTML5, CSS3 layouts (Flexbox, Grid), responsive design, and accessibility basics.',
        level: 'beginner',
        duration: '2-3 weeks',
        resources: [
          { title: 'freeCodeCamp — Responsive Web Design', url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/', type: 'course', free: true },
          { title: 'The Odin Project — HTML Foundations', url: 'https://www.theodinproject.com/paths/foundations/courses/foundations', type: 'course', free: true },
          { title: 'MDN — Learn Web Development', url: 'https://developer.mozilla.org/en-US/docs/Learn', type: 'docs', free: true },
        ],
      },
      {
        id: 'web-javascript',
        title: 'JavaScript Essentials',
        description: 'Master variables, functions, DOM manipulation, async/await, ES6+ features, and error handling.',
        level: 'beginner',
        duration: '3-4 weeks',
        resources: [
          { title: 'JavaScript.info — Modern JavaScript Tutorial', url: 'https://javascript.info/', type: 'docs', free: true },
          { title: 'freeCodeCamp — JavaScript Algorithms', url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/', type: 'course', free: true },
          { title: 'Traversy Media — JS Crash Course', url: 'https://www.youtube.com/watch?v=hdI2bqOjy3c', type: 'video', free: true },
        ],
      },
      {
        id: 'web-react',
        title: 'React.js',
        description: 'Component-based UI, hooks, state management, routing, and building single-page applications.',
        level: 'intermediate',
        duration: '4-5 weeks',
        resources: [
          { title: 'React Official Docs — Learn React', url: 'https://react.dev/learn', type: 'docs', free: true },
          { title: 'Scrimba — Learn React for Free', url: 'https://scrimba.com/learn/learnreact', type: 'course', free: true },
          { title: 'Net Ninja — Full React Tutorial', url: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9gZD-Tvwfod2gaISzfRiP9d', type: 'video', free: true },
        ],
      },
      {
        id: 'web-node',
        title: 'Node.js & Backend',
        description: 'Server-side JavaScript with Express, REST APIs, middleware, authentication, and database integration.',
        level: 'intermediate',
        duration: '3-4 weeks',
        resources: [
          { title: 'The Odin Project — NodeJS Path', url: 'https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs', type: 'course', free: true },
          { title: 'freeCodeCamp — APIs and Microservices', url: 'https://www.freecodecamp.org/learn/back-end-development-and-apis/', type: 'course', free: true },
          { title: 'Traversy Media — Node.js Crash Course', url: 'https://www.youtube.com/watch?v=fBNz5xF-Kx4', type: 'video', free: true },
        ],
      },
      {
        id: 'web-databases',
        title: 'Databases',
        description: 'SQL fundamentals, MongoDB/NoSQL, ORMs, data modeling, and query optimization.',
        level: 'intermediate',
        duration: '2-3 weeks',
        resources: [
          { title: 'SQLBolt — Interactive SQL Lessons', url: 'https://sqlbolt.com/', type: 'course', free: true },
          { title: 'MongoDB University — Free Courses', url: 'https://learn.mongodb.com/', type: 'course', free: true },
          { title: 'Fireship — SQL Explained in 100 Seconds', url: 'https://www.youtube.com/watch?v=zsjvFFKOm3c', type: 'video', free: true },
        ],
      },
      {
        id: 'web-deployment',
        title: 'Git, Testing & Deployment',
        description: 'Version control with Git, CI/CD pipelines, Docker basics, and deploying to Vercel/Railway.',
        level: 'advanced',
        duration: '2-3 weeks',
        resources: [
          { title: 'GitHub Skills — Interactive Git Courses', url: 'https://skills.github.com/', type: 'course', free: true },
          { title: 'Vercel Docs — Deploy a React App', url: 'https://vercel.com/docs/frameworks/vite', type: 'docs', free: true },
          { title: 'Fireship — Docker in 100 Seconds', url: 'https://www.youtube.com/watch?v=Gjnup-PuquQ', type: 'video', free: true },
        ],
      },
    ],
  },
  {
    id: 'ai-ml',
    title: 'AI & Machine Learning',
    icon: 'fas fa-brain',
    color: '#8b5cf6',
    description: 'From Python fundamentals to building and deploying machine learning models.',
    nodes: [
      {
        id: 'ai-python',
        title: 'Python Fundamentals',
        description: 'Core Python: data types, functions, OOP, file handling, and virtual environments.',
        level: 'beginner',
        duration: '2-3 weeks',
        resources: [
          { title: 'CS50P — Introduction to Python', url: 'https://cs50.harvard.edu/python/', type: 'course', free: true },
          { title: 'Automate the Boring Stuff with Python', url: 'https://automatetheboringstuff.com/', type: 'article', free: true },
          { title: 'Corey Schafer — Python Tutorials', url: 'https://www.youtube.com/playlist?list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU', type: 'video', free: true },
        ],
      },
      {
        id: 'ai-math',
        title: 'Math for ML',
        description: 'Linear algebra, calculus, probability, and statistics — the building blocks of every ML algorithm.',
        level: 'beginner',
        duration: '3-4 weeks',
        resources: [
          { title: '3Blue1Brown — Essence of Linear Algebra', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab', type: 'video', free: true },
          { title: 'Khan Academy — Statistics & Probability', url: 'https://www.khanacademy.org/math/statistics-probability', type: 'course', free: true },
          { title: 'StatQuest — Machine Learning', url: 'https://www.youtube.com/c/joshstarmer', type: 'video', free: true },
        ],
      },
      {
        id: 'ai-data',
        title: 'Data Analysis with NumPy & Pandas',
        description: 'Data wrangling, cleaning, visualization with Matplotlib/Seaborn, and exploratory data analysis.',
        level: 'intermediate',
        duration: '2-3 weeks',
        resources: [
          { title: 'Kaggle — Pandas Course', url: 'https://www.kaggle.com/learn/pandas', type: 'course', free: true },
          { title: 'freeCodeCamp — Data Analysis with Python', url: 'https://www.freecodecamp.org/learn/data-analysis-with-python/', type: 'course', free: true },
          { title: 'Corey Schafer — Pandas Tutorials', url: 'https://www.youtube.com/playlist?list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS', type: 'video', free: true },
        ],
      },
      {
        id: 'ai-sklearn',
        title: 'Classical Machine Learning',
        description: 'Supervised/unsupervised learning, model evaluation, feature engineering with Scikit-learn.',
        level: 'intermediate',
        duration: '4-5 weeks',
        resources: [
          { title: 'Kaggle — Intro to Machine Learning', url: 'https://www.kaggle.com/learn/intro-to-machine-learning', type: 'course', free: true },
          { title: 'Andrew Ng — Machine Learning Specialization', url: 'https://www.coursera.org/specializations/machine-learning-introduction', type: 'course', free: true },
          { title: 'Scikit-learn Official Tutorials', url: 'https://scikit-learn.org/stable/tutorial/', type: 'docs', free: true },
        ],
      },
      {
        id: 'ai-deep-learning',
        title: 'Deep Learning',
        description: 'Neural networks, CNNs, RNNs, transformers, and frameworks like TensorFlow/PyTorch.',
        level: 'advanced',
        duration: '5-6 weeks',
        resources: [
          { title: 'Fast.ai — Practical Deep Learning', url: 'https://course.fast.ai/', type: 'course', free: true },
          { title: 'PyTorch Official Tutorials', url: 'https://pytorch.org/tutorials/', type: 'docs', free: true },
          { title: '3Blue1Brown — Neural Networks', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi', type: 'video', free: true },
        ],
      },
      {
        id: 'ai-projects',
        title: 'ML Projects & Deployment',
        description: 'End-to-end ML projects, model serving with Flask/FastAPI, MLOps basics, and Kaggle competitions.',
        level: 'advanced',
        duration: '3-4 weeks',
        resources: [
          { title: 'Kaggle Competitions', url: 'https://www.kaggle.com/competitions', type: 'tool', free: true },
          { title: 'Made With ML — MLOps Course', url: 'https://madewithml.com/', type: 'course', free: true },
          { title: 'Krish Naik — End-to-End ML Projects', url: 'https://www.youtube.com/c/KrishNaik', type: 'video', free: true },
        ],
      },
    ],
  },
  {
    id: 'cybersecurity',
    title: 'Cybersecurity',
    icon: 'fas fa-shield-alt',
    color: '#ef4444',
    description: 'Learn to defend systems, find vulnerabilities, and think like a security professional.',
    nodes: [
      {
        id: 'cyber-networking',
        title: 'Networking Fundamentals',
        description: 'TCP/IP, DNS, HTTP/HTTPS, OSI model, subnetting, and packet analysis with Wireshark.',
        level: 'beginner',
        duration: '2-3 weeks',
        resources: [
          { title: 'Professor Messer — CompTIA Network+', url: 'https://www.professormesser.com/network-plus/n10-008/n10-008-video/n10-008-training-course/', type: 'video', free: true },
          { title: 'Cisco Networking Academy', url: 'https://www.netacad.com/courses/networking', type: 'course', free: true },
          { title: 'TryHackMe — Intro to Networking', url: 'https://tryhackme.com/room/introtonetworking', type: 'course', free: true },
        ],
      },
      {
        id: 'cyber-linux',
        title: 'Linux & Command Line',
        description: 'Linux administration, bash scripting, file permissions, process management, and system hardening.',
        level: 'beginner',
        duration: '2-3 weeks',
        resources: [
          { title: 'OverTheWire — Bandit Wargame', url: 'https://overthewire.org/wargames/bandit/', type: 'course', free: true },
          { title: 'Linux Journey', url: 'https://linuxjourney.com/', type: 'course', free: true },
          { title: 'TryHackMe — Linux Fundamentals', url: 'https://tryhackme.com/module/linux-fundamentals', type: 'course', free: true },
        ],
      },
      {
        id: 'cyber-web-sec',
        title: 'Web Security',
        description: 'OWASP Top 10, XSS, SQL injection, CSRF, authentication exploits, and secure coding practices.',
        level: 'intermediate',
        duration: '3-4 weeks',
        resources: [
          { title: 'PortSwigger Web Security Academy', url: 'https://portswigger.net/web-security', type: 'course', free: true },
          { title: 'OWASP Top 10', url: 'https://owasp.org/www-project-top-ten/', type: 'docs', free: true },
          { title: 'TryHackMe — Web Fundamentals', url: 'https://tryhackme.com/path/outline/web', type: 'course', free: true },
        ],
      },
      {
        id: 'cyber-crypto',
        title: 'Cryptography',
        description: 'Symmetric/asymmetric encryption, hashing, digital signatures, PKI, and TLS/SSL.',
        level: 'intermediate',
        duration: '2-3 weeks',
        resources: [
          { title: 'CryptoHack — Learn Cryptography', url: 'https://cryptohack.org/', type: 'course', free: true },
          { title: 'Khan Academy — Cryptography', url: 'https://www.khanacademy.org/computing/computer-science/cryptography', type: 'course', free: true },
          { title: 'Computerphile — Cryptography', url: 'https://www.youtube.com/playlist?list=PLzH6n4zXuckqmf_xUcvU5caZVoctP2ehL', type: 'video', free: true },
        ],
      },
      {
        id: 'cyber-ethical-hacking',
        title: 'Ethical Hacking & Pentesting',
        description: 'Reconnaissance, scanning, exploitation with Metasploit, privilege escalation, and report writing.',
        level: 'advanced',
        duration: '4-5 weeks',
        resources: [
          { title: 'TryHackMe — Complete Beginner Path', url: 'https://tryhackme.com/path/outline/beginner', type: 'course', free: true },
          { title: 'Hack The Box — Starting Point', url: 'https://app.hackthebox.com/starting-point', type: 'tool', free: true },
          { title: 'TCM Security — Ethical Hacking Course', url: 'https://www.youtube.com/watch?v=3FNYvj2U0HM', type: 'video', free: true },
        ],
      },
      {
        id: 'cyber-ctf',
        title: 'CTF Challenges & Certifications',
        description: 'Capture the Flag competitions, security certifications roadmap, and building a security portfolio.',
        level: 'advanced',
        duration: '3-4 weeks',
        resources: [
          { title: 'PicoCTF — Beginner CTFs', url: 'https://picoctf.org/', type: 'tool', free: true },
          { title: 'CTFtime — Competition Calendar', url: 'https://ctftime.org/', type: 'tool', free: true },
          { title: 'Professor Messer — CompTIA Security+', url: 'https://www.professormesser.com/security-plus/sy0-701/sy0-701-video/sy0-701-comptia-security-plus-course/', type: 'video', free: true },
        ],
      },
    ],
  },
];
